crawler_cool_down: 4
trading_fee: 0.0047
risk_free_rate_annual: 0.05
disable_logging: False
debug: True
default_backtest_params:
  institutional_weight: 0.6
  take_profit: 0.325
  trailing_stop_loss: 0.5
  fund_net_buying: 0.35
  number_fund_holdings: 0.45
  roe: 0.3
  revenue_growth: 0.1
  pe: 0.4
  number_of_stocks: 3
  initial_balance: 1000000
  stock_weight_option: "equal"

random_seed: 42

data_collection:
  start_date: "2022-01-01"
  end_date: "2025-01-31"

in_sample:
  start_date: "2023-02-01"
  end_date: "2024-01-31"

out_sample:
  start_date: "2024-02-01"
  end_date: "2025-01-31"

optuna:
  study_name: "in_sample_optimization"
  storage_name: "optuna_optimization"
  max_trials: 5000
